<template>
  <div class="sun">
    <ul>
      <li>用户帮助</li>
      <li>申请退款</li>
      <li>查看美团券密码</li>
      <li>常见问题</li>
      <li>用户协议</li>
      <li>隐私政策</li>
      <li>反诈骗公告</li>
      <li>消费者权益保障</li>
      <li>美团服务</li>
      <li>美团外卖</li>
      <li>美团酒店</li>
      <li>猫眼电影</li>
      <li>美团配送</li>
      <li>美团云</li>
      <li>大众点评</li>
      <li>美团民宿</li>
      <li>无人配送</li>
    </ul>
    <ul>
      <li>商家合作</li>
      <li>美团餐饮商户中心</li>
      <li>美食商家入驻(非外卖)</li>
      <li>美团外卖开店申请</li>
      <li>美团收银官网</li>
      <li>外卖配送加盟申请</li>
      <li>美团点评餐饮学院</li>
      <li>酒店商家入驻</li>
      <li>境内度假商家入驻</li>
      <li>综合商家入驻</li>
      <li>美团民宿房东商家入驻</li>
      <li>商家开票申请</li>
      <li>美团点评智能收银机</li>
      <li>美团点评餐饮开放平台</li>
      <li>美团点评收单</li>
      <li>免费使用美团排队</li>
      <li>快驴进货商家合作</li>
      <li>美团闪购商家入驻</li>
    </ul>
    <ul>
      <li>代理商加盟</li>
      <li>美团外卖代理商招募</li>
      <li>到店餐饮代理商招募</li>
      <li>非餐饮代理商招募</li>
      <li>美团联盟</li>
      <li>美团收银招募线上分销商</li>
      <li>美团点评5S服务商招募</li>
      <li>美团收单渠道代理商招募</li>
      <li>美团规则</li>
      <li>规则中心</li>
      <li>规则目录</li>
      <li>规则评议院</li>
    </ul>
    <ul>
      <li>关注美团</li>
      <li>美团新浪微博</li>
      <li>公司信息</li>
      <li>关于我们</li>
      <li>投资者关系</li>
      <li>加入我们</li>
      <li>商户诚信公约及管理办法</li>
      <li>保险经纪资质</li>
      <li>廉正举报</li>
      <li>廉政邮箱</li>
      <li>知识产权</li>
      <li>知识产权维权平台</li>
    </ul>
    <ul>
        <li>消费者服务热线</li>
        <li>外卖消费者：10109777</li>
        <li>猫眼消费者：10105335</li>
        <li>其他消费者：10107888</li>
        <li>商家服务热线</li>
        <li>外卖&餐饮商家：10105557</li>
        <li>休闲娱乐、丽人、ktv、教育、结婚、亲子、家装等商家：10100107</li>
        <li>投诉举报热线</li>
        <li>违法和不良信息举报电话：4006018900</li>
        <li>举报邮箱：tousujubao@meituan.com</li>
    </ul>
  </div>
</template>
<style lang="less" scoped>
@import "../../assets/styles/footer/bott.less";
</style>
